### ISSUE TITLE
DO NOT just straight up put your whole bloody config folder

### ISSUE THREAD

**Issue by alanxyz** [WalrusGumboot/dotfiles#1]
a

**Comment by alanxyz** [comment]
Seems to also include your cookies for sites which log you in, I’m not actually going to try this but please realise you should close this repository and make a new one with only the configuration files for stuff like poly bar and your window manager and shit which doesn’t have sensitive info.
I should note I cannot test if this is actually the case, on mobile currently

**Comment by WalrusGumboot** [comment]
I've deleted the important (read: potentially vulnerable) directories.
